# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcaf975b926a83dc33ab2d414aca7cbe2bf74afac7965b1229c18b3187dc0fa6101c3d5ae331f7f05324b9e7bae94d7c2ba32f7df5c2ea3363be62536f13c62

test:
  secret_key_base: 1815c432b23e9aa2a9dffb8044972d597a6f3ab8a47ba3e439eb43ca369e9ae56150054f9f266462da5adca45c633feef34f010e920180d2c8fbba27c0dc1747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
